name: Construieste APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Construieste APK cu Buildozer
      uses: kivy/buildozer-action@main
      id: buildozer
      with:
        filename: buildozer.spec

    - name: Salveaza APK-ul ca fisier descarcabil
      uses: actions/upload-artifact@v4
      with:
        name: pachet-apk
        path: ${{ steps.buildozer.outputs.filename }}
